name: dockpsa salida en texto plano
on:
  workflow_dispatch: # Ejecución manual

jobs:
  create_file:
    runs-on: [self-hosted, linux, test-deploy]
    
    steps:
      - name: Conectar a 172 y crear archivo
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_172 }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY_172 }}
          script: |
            echo "Conectado a $(hostname)"
            # cambiando directorio CICD
            cd CICD
            echo "Creando archivo dockpsa.txt..."
            echo "Archivo creado por GitHub Actions el $(date)" > dockpsa.txt
            echo "" >> dockpsa.txt
            docker ps -a >> dockpsa.txt
            ls -l dockpsa.txt
            # Enviar aviso
    env:
        TEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK_URL }}
      run: |
        cd /home/GIT
        
        # Guardamos la salida de docker en una variable en lugar de un archivo de texto
        # (Aunque si necesitas deploy.txt para otra cosa, puedes usar: docker ps -a | tee deploy.txt)
        DOCKER_OUTPUT=$(docker ps -a)
        
        # Utilizamos 'jq' para formatear correctamente los saltos de línea de la consola a un JSON válido para Teams
        JSON_PAYLOAD=$(jq -n \
          --arg title "**Deploy realizado proyecto: sa-wfm-datahub-api** 🚀" \
          --arg body "<pre>$DOCKER_OUTPUT</pre>" \
          '{text: ($title + "<br><br>" + $body)}')
        
        # Enviamos el aviso a Teams usando curl
        curl -s -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$TEAMS_WEBHOOK"
        
        echo '###### fin del workflow ######'
