# Reinicio Docker

name: Docker restart

on:
  workflow_dispatch:

jobs:
    runs-on: self-hosted

    # Pasos a ejecutar
    steps:
      
      - name: Detener contenedor
        run: |
          echo "Deteniendo contenedor"
          docker stop manager-api-gateway
      - name: Esperar 20 segundos
        run: |
          echo "Esperar 20 segundos"
          sleep 20
      - name: Iniciar contenedor
        run: |
          echo "Levantando contenedor"
          docker start manager-api-gateway

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
